build:
  version: "3.0"

banks:
  message: "Welcome to YesBank accounts related QA APIs "
  contactDetails:
    name: "Vijay kumar QA lead"
    email: "vijaycool294@gmail.com"
  onCallSupport:
    - 7503304263
