build:
  version: "1.0"

cards:
  message: "Welcome to YesBank accounts related QA APIs "
  contactDetails:
    name: "vijay kumar prod"
    email: "vijaycool294@gmail.com"
  onCallSupport:
    - 7503304263