server:
  port: 8086

spring:
  application:
    name: notifications
  profiles:
    active: "prod"

  config:
    import: optional:configserver:http://localhost:8071

  datasource:
    url: jdbc:postgresql://localhost:5432/yes_bank
    username: postgres
    password: vijay
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "com.yesbank.notification.dto"

    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: manual

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
notification:
  kafka:
    topic: notification-events
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#    register-with-eureka: true
#    fetch-registry: true
#
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.mail: INFO
    com.yesbank.notification: DEBUG